/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LobbiesIndexRouteImport } from './routes/lobbies/index'
import { Route as LobbiesNewRouteImport } from './routes/lobbies/new'
import { Route as LobbiesLobbyIdRouteImport } from './routes/lobbies/$lobbyId'
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbiesIndexRoute = LobbiesIndexRouteImport.update({
  id: '/lobbies/',
  path: '/lobbies/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbiesNewRoute = LobbiesNewRouteImport.update({
  id: '/lobbies/new',
  path: '/lobbies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbiesLobbyIdRoute = LobbiesLobbyIdRouteImport.update({
  id: '/lobbies/$lobbyId',
  path: '/lobbies/$lobbyId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/lobbies/$lobbyId': typeof LobbiesLobbyIdRoute
  '/lobbies/new': typeof LobbiesNewRoute
  '/lobbies/': typeof LobbiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/lobbies/$lobbyId': typeof LobbiesLobbyIdRoute
  '/lobbies/new': typeof LobbiesNewRoute
  '/lobbies': typeof LobbiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/lobbies/$lobbyId': typeof LobbiesLobbyIdRoute
  '/lobbies/new': typeof LobbiesNewRoute
  '/lobbies/': typeof LobbiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/$gameId'
    | '/lobbies/$lobbyId'
    | '/lobbies/new'
    | '/lobbies/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/$gameId' | '/lobbies/$lobbyId' | '/lobbies/new' | '/lobbies'
  id:
    | '__root__'
    | '/'
    | '/games/$gameId'
    | '/lobbies/$lobbyId'
    | '/lobbies/new'
    | '/lobbies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  LobbiesLobbyIdRoute: typeof LobbiesLobbyIdRoute
  LobbiesNewRoute: typeof LobbiesNewRoute
  LobbiesIndexRoute: typeof LobbiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobbies/': {
      id: '/lobbies/'
      path: '/lobbies'
      fullPath: '/lobbies/'
      preLoaderRoute: typeof LobbiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobbies/new': {
      id: '/lobbies/new'
      path: '/lobbies/new'
      fullPath: '/lobbies/new'
      preLoaderRoute: typeof LobbiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobbies/$lobbyId': {
      id: '/lobbies/$lobbyId'
      path: '/lobbies/$lobbyId'
      fullPath: '/lobbies/$lobbyId'
      preLoaderRoute: typeof LobbiesLobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  LobbiesLobbyIdRoute: LobbiesLobbyIdRoute,
  LobbiesNewRoute: LobbiesNewRoute,
  LobbiesIndexRoute: LobbiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
